services:
  - type: web
    name: rynix-backend
    env: node
    plan: free
    region: oregon 
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: rynix-redis
          property: connectionString
      - fromGroup: rynix-secrets

  - type: redis
    name: rynix-redis
    plan: free
    region: oregon
